import type { CareAlert, Patient } from "../shared/types/types";

export const patients: Patient[] = [
  {
    id: "PT-1042",
    name: "Ananya Rao",
    age: 64,
    condition: "Hypertension",
    careTeam: "Cardiology",
    nextVisit: "Today, 3:30 PM",
    risk: "medium",
    adherence: 82,
    status: "Needs review",
    lastUpdated: "12 min ago",
    vitals: { heartRate: 88, bloodPressure: "142/91", oxygen: 97 },
    clinicalSummary: {
      focusAreas: ["Review recent blood pressure logs", "Check dietary sodium intake"],
      riskNote: "Elevated BP trends over the last 48 hours",
    },
  },
  {
    id: "PT-1187",
    name: "Meera Sharma",
    age: 57,
    condition: "Type 2 Diabetes",
    careTeam: "Endocrinology",
    nextVisit: "Tomorrow, 10:00 AM",
    risk: "high",
    adherence: 66,
    status: "Critical watch",
    lastUpdated: "24 min ago",
    vitals: { heartRate: 92, bloodPressure: "136/84", oxygen: 96 },
    clinicalSummary: {
      focusAreas: ["Medication adherence review", "Remote vitals sync"],
      riskNote: "Escalate elevated risk changes to specialist team",
    },
  },
  {
    id: "PT-1215",
    name: "Rohan Iyer",
    age: 43,
    condition: "Post-op recovery",
    careTeam: "Orthopedics",
    nextVisit: "Apr 30, 11:15 AM",
    risk: "low",
    adherence: 94,
    status: "Stable",
    lastUpdated: "39 min ago",
    vitals: { heartRate: 76, bloodPressure: "122/78", oxygen: 99 },
    clinicalSummary: {
      focusAreas: ["Physical therapy progress check", "Assess pain management plan"],
    },
  },
  {
    id: "PT-1301",
    name: "Sara Thomas",
    age: 71,
    condition: "COPD monitoring",
    careTeam: "Pulmonology",
    nextVisit: "May 1, 2:00 PM",
    risk: "high",
    adherence: 71,
    status: "Critical watch",
    lastUpdated: "1 hr ago",
    vitals: { heartRate: 101, bloodPressure: "130/82", oxygen: 91 },
    clinicalSummary: {
      focusAreas: ["Continuous oxygen saturation monitoring", "Inhaler technique review"],
      riskNote: "Oxygen dipped below 92%; monitor closely",
    },
  },
  {
    id: "PT-1364",
    name: "Kabir Menon",
    age: 36,
    condition: "Asthma",
    careTeam: "Respiratory Care",
    nextVisit: "May 2, 9:45 AM",
    risk: "low",
    adherence: 91,
    status: "Stable",
    lastUpdated: "2 hrs ago",
    vitals: { heartRate: 72, bloodPressure: "118/76", oxygen: 98 },
    clinicalSummary: {
      focusAreas: ["Review asthma action plan", "Check rescue inhaler usage"],
    },
  },
  {
    id: "PT-1408",
    name: "Neha Kapoor",
    age: 52,
    condition: "Renal follow-up",
    careTeam: "Nephrology",
    nextVisit: "May 2, 4:20 PM",
    risk: "medium",
    adherence: 79,
    status: "Needs review",
    lastUpdated: "3 hrs ago",
    vitals: { heartRate: 84, bloodPressure: "138/86", oxygen: 97 },
    clinicalSummary: {
      focusAreas: ["Review recent renal panel results", "Fluid intake assessment"],
      riskNote: "Requires follow-up on declining eGFR trends",
    },
  },
];

export const careAlerts: CareAlert[] = [
  {
    id: "AL-41",
    title: "COPD oxygen dip",
    body: "Sara Thomas has oxygen saturation below the care threshold.",
    severity: "high",
    time: "5 min ago",
    patientId: "PT-1301",
  },
  {
    id: "AL-42",
    title: "Medication adherence",
    body: "Meera Sharma missed two glucose medication check-ins this week.",
    severity: "high",
    time: "18 min ago",
    patientId: "PT-1187",
  },
  {
    id: "AL-43",
    title: "Follow-up due",
    body: "Ananya Rao is ready for clinician review before today's visit.",
    severity: "medium",
    time: "42 min ago",
    patientId: "PT-1042",
  },
];

export const weeklyAdmissions = [42, 51, 48, 62, 57, 69, 73];
export const riskTrend = [12, 14, 13, 17, 19, 16, 15];
